### DISCUSSION TITLE
Displaying Alerts, Violations, and Warnings

### DISCUSSION THREAD

**Discussion by GeekMasher** [advanced-security/policy-as-code#33] [General]
By default in v1 and v2+ of [Policy as Code](https://github.com/advanced-security/policy-as-code) it does not show the violations by default. This is due to possibly leaking information in logs and best practice is to not show them and opt in to show the results.

Right now you have to add a argument to the Action:

```yml
# Policy as Code
- name: Advance Security Policy as Code
  uses: advanced-security/policy-as-code@main
  with:
    # ...
    argvs: "--display"
```

With version v3+, this option will be moved into policy file itself versus in Action.
