### ISSUE TITLE
Reporting Block

### ISSUE THREAD

**Issue by GeekMasher** [advanced-security/policy-as-code#18]
### Description

When an Action is run, there are some post-reporting requirements that might be wanted versus just halting the workflow. There are a few different reporting "plugins" that could be developed.

### Propose Solution

```yml
reporting:
  repository_topics:
    compliant: ""
    noncompliant: "noncompliant"

  issues_summary:
    title: "[GHAS Compliance] {{owner}}/{{repository}}"
    repository: GeekMasherOrg/security

    assignees:
      - GeekMasher

    template: summary.md

  projectboard:
    name: "Security Compliance"
```
