### ISSUE TITLE
Unknown exception for Dependabot policy

### ISSUE THREAD

**Issue by jan-verb** [advanced-security/policy-as-code#19]
**Describe the bug**

**To Reproduce**
With the below config...
```
name: 'Dependabot Review'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@main
        with:
          token: ${{ secrets.DEPENDABOT_API_TOKEN }} # My GH PAT, which works with the Dependabot API
          argvs: --display
          policy: GeekMasherOrg/ghas-compliance
          policy-path: policy.yml
```
my workflow fails with the following error:
```
Dependabot Alerts from Pull Request
[72](https://github.com/reverbdotcom/edge-acl/actions/runs/4948715728/jobs/8849842456?pr=70#step:3:77)
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
[73](https://github.com/reverbdotcom/edge-acl/actions/runs/4948715728/jobs/8849842456?pr=70#step:3:78)
  Error: Unable to parse PURL :: 
[74](https://github.com/reverbdotcom/edge-acl/actions/runs/4948715728/jobs/8849842456?pr=70#step:3:79)
  Total unacceptable alerts :: 0
[74](https://github.com/reverbdotcom/edge-acl/actions/runs/4948715728/jobs/8849842456?pr=70#step:3:79)
  Acceptable risk and no threshold reached.
```

**Expected behavior**
I expect the workflow to output the Dependabot findings in my repo.

**Screenshots**
<img width="965" alt="image" src="https://github.com/advanced-security/policy-as-code/assets/56366891/fd537589-9719-4f23-8d45-fde4c603ac04">
