### ISSUE TITLE
Dependabot created_at returning None

### ISSUE THREAD

**Issue by pritchyspritch** [advanced-security/policy-as-code#21]
**Describe the bug**
I've found that running policy-as-code with a remediation time set in my config under dependabot, will throw the following error:

`Error: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'`

Upon investigation, it appears that [line 185 in checks.py](https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/checks.py#L185) is always returning None in my case. Possibly relating to the ghastoolkit library? I've checked the API myself and all of the dependabot alerts have a `created_at` date set. It looks like the toolkit is calling the createdAt() in dependencyalert.py, which should return the time, but fails to do so: 

https://github.com/GeekMasher/ghastoolkit/blob/main/src/ghastoolkit/supplychain/dependencyalert.py#L26

I believe the line actually throwing the error is [line 278 in policy.py](https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/policy.py#L278). But as said above, I think the actual issue is coming from the ghastoolkit failing to return the dependabot `created_at` value appropriately.

**To Reproduce**
1. workflow:
```yaml
name: Fully Compliant

on:
  push:
    branches: [ main, ghas-pac ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compliance:
    runs-on: ubuntu-latest

    steps:
    - name: Advance Security Compliance Action
      uses: advanced-security/policy-as-code@v2.3.1
      with:
        # Set the severity levels which to set the threshold. All previous 
        # severities are included so selecting 'error' also selects 'critical' and 
        # 'high' along with 'error'.
        severity: error

        # Repository owner/name.
        # This can be setup using a separate repository to the one being analysed 
        #  for security compliance
        repository: <repo>

        # The owner/repo of where the policy is stored
        # This generally is primarily used for a single repository that defines 
        #  your organizations security policy
        policy: <repo>

        # The path where the policy lives. This might be in either the current 
        #  repository or in a remote repository.
        policy-path: .github/policy/ghas-policy.yml

        # The branch you want to target using `policy` argument
        policy-branch: ghas-pac

        # GitHub Personal Access Token to access the GitHub API.
        # Secret Scanning and Dependabot do not allow their resources to be
        #  exposed to Actions so this might need to be set using a token that has 
        #  the ability to access the resources
        token: ${{ secrets.POLICY_PAT }}

        # [optional] GitHub reference, this is passed in by Actions at runtime
        ref: refs/heads/main

        # [optional] What course of action to take upon discovering security issues that pass
        # threshold?
        action: break
```
2. policy:
```yaml
name: High Threat Model Policy

codescanning:
  level: high
  remediate:
    critical: 5
    high: 30
    medium: 60

# Dependency Security Alters
dependabot:
  level: high  
  remediate:
    critical: 5
    high: 30
    medium: 60
  

secretscanning:
  level: all

# Dependency Licensing Alerts
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

  warnings:
    # Warning is the dependency isn't known
    ids:
      - Other
      - NA
```
**Expected behavior**
Dependabot checks to finish without error, by returning the `created_at` date and allowing the alert time to be calculated.

**Screenshots**
![image](https://github.com/advanced-security/policy-as-code/assets/47423802/378f5b5d-3f56-4050-a0af-d3fea16d52f0)

**build**
GitHub Actions Ubuntu-latest
