### ISSUE TITLE
Fails to clone policy repo using GitHub App auth

### ISSUE THREAD

**Issue by Pradoxzon** [advanced-security/policy-as-code#30]
**Describe the bug**
When running Policy as Code using a [GitHub App for authentication](https://github.com/advanced-security/policy-as-code/blob/main/docs/samples/appauthentication.md) and when using a policy yml defined in a separate repository, the PaC action fails to clone the repository containing the policy file. See the screenshot attached below for reference.

It appears that [the `github_app` property](https://github.com/GeekMasher/ghastoolkit/blob/main/src/ghastoolkit/octokit/github.py#L179) of the GitHub class in ghastoolkit is never set to true by PaC, leading to the incorrect use of the token when cloning the repo in [the `clone_url` function](https://github.com/GeekMasher/ghastoolkit/blob/main/src/ghastoolkit/octokit/github.py#L92).

A simple fix would be to pass `arguments.is_github_app_token` to the GitHub class after the call to `GitHub.init()` in `__main.py__`, [line 84](https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/__main__.py#L84).

**Description of Use Case**
My use case is running PaC in a different repo than the repo containing the policy files. Both repos are owned by an organization. Everything works fine using a PAT for auth, but switching to GitHub App auth and adding `--is-github-app-token` to the argvs input caused the errors.

**To Reproduce**
1. workflow file:

```yml
name: License Compliance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-compliance:
    runs-on: ubuntu-latest

    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_KEY }}
      
    - name: Advanced Security Policy as Code
      uses: advanced-security/policy-as-code@v2.3.4
      with:
        policy: <org/repo>
        policy-path: <policy-file.yml>
        policy-branch: <branch>
        token: ${{ steps.generate_token.outputs.token }}
        
        argvs: '--is-github-app-token --display --disable-dependabot --disable-secret-scanning --disable-code-scanning'
```

2. policy file:
This issue should be reproducible with any policy file, but this is the one I was running tests with.

```yml
name: License Compliance Policy

licensing:
  warnings:
    ids:
      - MIT
      - MIT-0
      - BSD-1-Clause
      - BSD-2-Clause
      - BSD-3-Clause
      - Other
      - NA

  conditions:
    ids:
      - MIT
      - MIT-0
      - BSD-1-Clause
      - BSD-2-Clause
      - BSD-3-Clause
      - Other
      - NA
```

**Expected behavior**
Policy as Code properly clones the policy repo using the GitHub App token.

**Screenshots**
![image](https://github.com/advanced-security/policy-as-code/assets/25668381/52873c63-2fda-4266-9344-b4e06dffcfa1)

**Build**
GitHub Actions using ubuntu-latest
