### ISSUE TITLE
License warnings don't use ignore list

### ISSUE THREAD

**Issue by Pradoxzon** [advanced-security/policy-as-code#46]
**Describe the bug**
I'm not sure if this is a true bug in the functionality or if this design was intended.  
Currently, `checkDependencyLicensing()` in `checks.py` [on line 227](https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/checks.py#L227) does not use the ignore lists for warnings. The list of warnings is created and handled before the ignore lists are created.

**To Reproduce**
1. Create a licensing policy that contains a list of licenses for `warnings`, `conditions`, and `ignores`
2. Ensure the ignores list shares at least 1 license with the warnings and conditions lists
3. Run the policy on a repo that contains dependencies with the license(s) in the ignores list
4. Observe that warnings are still generated for the license(s) in the ignores list

Example policy:
```yml
name: License Compliance Testing Policy

general:
  level: none

licensing:
  warnings:
    ids:
      - MIT
      - MIT-0
      - BSD-1-Clause
      - BSD-2-Clause
      - BSD-3-Clause
      - Other
      - NA

  conditions:
    ids:
      - MIT
      - MIT-0
      - BSD-1-Clause
      - BSD-2-Clause
      - BSD-3-Clause
      - Other
      - NA

  ignores:
    ids:
      - MIT
```

**Expected behavior**
As a user, I would generally expect an ignore list to apply to apply to both warnings and violations. I don't need to see a warning for a dependency/license that I already know I want to ignore.

**Build**
GitHub Actions, Policy as Code version 2.3.7, using ubuntu-latest
