### ISSUE TITLE
licensing - total dependency graph 0 on pull-request workflow

### ISSUE THREAD

**Issue by eidottermihi** [advanced-security/policy-as-code#54]
**Describe the bug**

When the policy-is-code Action is run on a pull-request (scanning the non-default branch), License checking does not work because the dependency graph includes `0` dependencies. 

When the action is run on the default branch, License checking works.

**To Reproduce**

Workflow
```yaml
jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.4.0
        with:
          policy-path: .github/policies/custom.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          argvs: "--disable-dependabot --disable-secret-scanning --disable-code-scanning --display"
```

Policy:
```yaml
name: custom

# Dependency Licensing Alerts
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

  warnings:
    # Warning is the dependency isn't known
    ids:
      - Other
      - NA
```

Open a PR and check the output of the action.

**Expected behavior**

Dependency Graph should be calculated with >0 dependencies.

**Screenshots**

action on PR (see https://github.com/it-at-m/appswitcher-vue/actions/runs/5711495958/job/15473216682)

![grafik](https://github.com/advanced-security/policy-as-code/assets/2780736/d6eafc92-889b-4f4f-8153-c983348cd8f2)

action on main branch (see https://github.com/it-at-m/appswitcher-vue/actions/runs/5711336691/job/15472815170)

![grafik](https://github.com/advanced-security/policy-as-code/assets/2780736/101c94c9-8cc9-4a17-92f7-f32b87797103)

**Additional context**

I noticed **Dependencies from Pull Request** in the action log - does this mean the scan on a PR detects "changed dependencies" and therefore just scans these dependencies?
