### ISSUE TITLE
Support for multiple tokens

### ISSUE THREAD

**Issue by Pradoxzon** [advanced-security/policy-as-code#62]
### Description
I noticed that Policy as Code does not work across multiple organizations when using GitHub Application tokens due to limitations with the tokens.  
GitHub App tokens are scoped to a single organization regardless of which orgs the app is installed on. This means that if the Policy as Code reusable workflow is defined in a separate organization and the policy is defined in a separate yml file instead of inline in the workflow, the PaC workflow repo can't be cloned since the GH App token doesn't have access to that organization. See the chart below for an illustration and the permissions needed for each situation.

I was recommended the [peter-murray/workflow-application-token-action](https://github.com/peter-murray/workflow-application-token-action) to generate the GH App token since it allows the user to specify the organization to scope the token to. This works and allows me to scope the token to the other organization, and PaC is able to clone the reusable workflow repo.  
However, the token then doesn't have permission to the calling repo since it's scoped to the other org (unable to read alerts, etc.).

```mermaid
flowchart TB
  subgraph sameorg [Same Organization]
    subgraph sorg1 [Org Alpha]
      direction TB
      work1(Workflow Repo<br>Permissions)
      repo1(Repo A<br>Permissions)
      w1perms("- Read contents (clone)")
      r1perms("- Read contents<br>- Read security events<br>- Read Dependabot alerts<br>- Read secret scanning alerts<br>- Read & Write pull requests")
      work1 --- w1perms
      repo1 --- r1perms
    end
  end
  subgraph difforg [Separate Organizations]
    direction LR
    subgraph dorg1 [Org Alpha]
      work2(Workflow Repo<br>Permissions)
      w2perms("- Read contents (clone)")
      work2 --- w2perms
    end
    subgraph dorg2 [Org Bravo]
      repo2(Repo B<br>Permissions)
      r2perms("- Read contents<br>- Read security events<br>- Read Dependabot alerts<br>- Read secret scanning alerts<br>- Read & Write pull requests")
      repo2 --- r2perms
    end
    dorg1 ~~~ dorg2
  end
```

### Propose Solution
Adding a feature to Policy as Code that allows the optional use of multiple tokens would solve this issue.  On the PaC side this would be a relatively small change. Two optional input parameters would need to be added for the token and a flag for if it's a GH App token, essentially a copy of the `--github-token` and `--is-github-app-token` arguments.

See PR #61 for a draft/suggestion of how this could be implemented in PaC.

This feature will also require changes to ghastoolkit to support multiple tokens. Currently the `Repository` class uses the static/singleton token information stored in the `GitHub` class. This means that while multiple `Repository` instances can be created, only a single token can be stored and is shared by all `Repository` instances. The `GitHub` and/or `Repository` classes would need to be modified to support multiple tokens.  
For two suggestions:
- The `GitHub` class could be updated to store multiple tokens, with a mechanism for `Repository` instances to grab the correct token
- The `Repository` class could have a mechanism to override or use it's own token instead of the `GitHub` class's token
  - Essentially use the `GitHub` class's token as a fallback

**Comment by GeekMasher** [comment]
@Pradoxzon can you please check v2.5.0 release to make sure everything works.

https://github.com/advanced-security/policy-as-code/releases/tag/v2.5.0

**Comment by Pradoxzon** [comment]
@GeekMasher v2.5.0 works great and resolves the issue!

Here is an example yml using the multiple tokens for reference, could be added to documentation examples if needed.

```yml
name: Security Policy Compliance

on:
  workflow_call:
    inputs:
      GH_RUNNER:
        required: false
        type: string
        default: "self-hosted"
    # A GitHub App ID and private key are required to run this workflow
    secrets:
      GH_APP_ID:
        required: True
      GH_APP_KEY:
        required: True
  
jobs:
  policy-as-code:
    name: Policy as Code
    runs-on: ${{ inputs.GH_RUNNER == 'self-hosted' && fromJSON('[ "self-hosted", "Linux" ]') || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        # List of policies to run
        policies: [ 'policy-a.yml', 'policy-b.yml' ]

    steps:
    - name: Generate policy repo token
      id: generate_repo_token
      uses: peter-murray/workflow-application-token-action@v2.1.0
      with:
        application_id: ${{ secrets.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}

    - name: Generate calling repo token
      id: generate_policy_token
      uses: peter-murray/workflow-application-token-action@v2.1.0
      with:
        application_id: ${{ secrets.GH_APP_ID }}
        application_private_key: ${{ secrets.GH_APP_KEY }}
        organization: Other-Org
      
    - name: Advanced Security Policy as Code
      uses: advanced-security/policy-as-code@v2.5.0
      with:
        policy: Other-Org/workflow-repo
        policy-path: ${{ matrix.policies }}
        policy-branch: main
        
        token: ${{ steps.generate_repo_token.outputs.token }}
        policy-repo-token: ${{ steps.generate_policy_token.outputs.token }}
        argvs: '--is-github-app-token --is-policy-github-app-token --display --pr-comment'
```
